#!/usr/bin/sh
#
# A wrapper around fzf so that we can cd to directories instantly
#

fzf > fzf.txt

length=$(cat fzf.txt | wc -c)

a=$(cat fzf.txt | rev | cut -f 2- -d "/" | rev)

echo "$a"

rm -r fzf.txt

cd "$a"
